---
# Playbook to deploy all the stuff and its components
- name: Install and deploy everything
  hosts: localwebserver
  gather_facts: false
  become: true
  roles:
      - deploy-database
      - deploy-phpmyadmin
